### ISSUE TITLE
Setup Your Kanaban Board

### ISSUE THREAD

**Issue by bushmusi** [mwafrika/final_capstone_frontend#12]
### We are in a team of Three(3)
![Screenshot from 2022-07-14 12-21-47](https://user-images.githubusercontent.com/35783481/178949484-ffad1779-326b-49e6-8ed7-e1205ac98c6a.png)

**Comment by MuriloRoque** [comment]
Hi @bushmusi, @Abenezer-Tilahun, @mwafrika,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
